### ISSUE TITLE
Doesn't work with Ready or Not

### ISSUE THREAD

**Issue by parasiteoflife** [matyalatte/LocRes-Builder#1]
I'm trying to translate the game but when I drop the locmeta file or use the command line manually I always get:

```
LocRes Builder ver0.1.0 by matyalatte
Loading C:\Ready Or Not\ReadyOrNot\Content\Paks\pakchunk0-WindowsNoEditor\ReadyOrNot\Content\Localization\Game\Game.locmeta...
actual: 1
expected: 0
Traceback (most recent call last):
  File "C:\Programs (2)\locbuilder\src\main.py", line 33, in <module>
    locres = LocalizationResources.load(file)
  File "C:\Programs (2)\locbuilder\src\locres.py", line 221, in load
    meta = LocMeta.load(meta_path)
  File "C:\Programs (2)\locbuilder\src\locres.py", line 180, in load
    check(version, 0, msg='Unsupported version. {}'.format(version))
  File "C:\Programs (2)\locbuilder\src\io_util.py", line 22, in check
    raise RuntimeError(msg)
RuntimeError: Unsupported version. 1
```

**Comment by matyalatte** [comment]
I only tested the tool with a game, so it's uncompatible with other format versions.
Can you share your .locres and .locmeta files?
I'll add support for the version.

But please don't upload the files here.
DM to me with [discord](https://discord.gg/Qx2Ff3MByF) or Twitter(@MatyaModding).
Or send me an email (matyalatte@gmail.com)

**Comment by parasiteoflife** [comment]
Thanks for looking into this, I sent you a dm in discord-

**Comment by matyalatte** [comment]
Supported locmeta ver1 at [v0.1.2](https://github.com/matyalatte/LocRes-Builder/releases/tag/v0.1.2).
